# Generated by Django 5.2.3 on 2025-07-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_cafe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidocafe',
            old_name='tamanio',
            new_name='tamano',
        ),
    ]
