# Generated by Django 5.2.3 on 2025-07-07 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_cafe', '0002_rename_tamanio_pedidocafe_tamano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidocafe',
            name='tamano',
        ),
    ]
