# Generated by Django 5.2.3 on 2025-07-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_cafe', '0003_remove_pedidocafe_tamano'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocafe',
            name='tamano',
            field=models.CharField(choices=[('pequenio', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], default='mediano', max_length=10),
            preserve_default=False,
        ),
    ]
