# Generated by Django 5.2.3 on 2025-07-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_cafe', '0004_pedidocafe_tamano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocafe',
            name='ingredientes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
