# Generated by Django 5.2.3 on 2025-07-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_cafe', '0005_alter_pedidocafe_ingredientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocafe',
            name='tamano',
            field=models.CharField(choices=[('pequeno', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=10),
        ),
    ]
