# Generated by Django 5.2.3 on 2025-07-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_cafe', '0006_alter_pedidocafe_tamano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocafe',
            name='ingredientes',
            field=models.CharField(max_length=255),
        ),
    ]
